module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        envName: 'APP_ENV',
        moduleName: '@env',
        path: '.env',
        blocklist: null,
        allowlist: null,
        blacklist: null, // DEPRECATED
        whitelist: null, // DEPRECATED
        safe: false,
        allowUndefined: true,
        verbose: false,
      },
    ],
    [
      'module-resolver',
      {
        // root: ['./src'],
        alias: {
          '@src': './src',
          '@assets': './src/assets/',
          '@images': './src/assets/images/',
          '@icons': './src/assets/icons/',
          '@svgs': './src/assets/svgs/',
          '@components': './src/components/',
          '@config': './src/config/',
          '@constants': './src/constants/',
          '@hooks': './src/hooks/',
          '@screens': './src/screens/',
          '@services': './src/services/',
          '@types': './src/types/',
          '@utils': './src/utils/',
          '@i18n': './src/i18n/',
          '@api': './src/api/',
          '@models': './src/models/',
          '@queryClient': './src/queryClient/',
          '@styles': './src/styles/',
          '@containers': './src/containers/',
          '@reduxStore': './src/redux-store/',
        },
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
          '.png',
          '.jpg',
          '.jpeg',
          '.svg',
        ],
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
