const Images = {
  EyeAbleIcon: require('@icons/eye.png'),
  EyeDisableIcon: require('@icons/eyeClose.png'),
  AddIcon: require('@icons/add.png'),
  // BackBtn: require('../../assets/icons/backArrow.png'),
  // User: require('../../assets/icons/user.png'),
  // Lock: require('../../assets/icons/lock.png'),
  // FaceIcon: require('../../assets/icons/faceIcon.png'),
  // TouchID: require('../../assets/icons/TouchID.png'),
  // MessagesIcon: require('../../assets/icons/messagesIcon.png'),
  // PendingTaskIcon: require('../../assets/icons/pendingTaskIcon.png'),
  // SalesIcon: require('../../assets/icons/salesIcon.png'),
  // OperationsIcon: require('../../assets/icons/operationsIcon.png'),
  // AssignmentsIcon: require('../../assets/icons/assignmentsIcon.png'),
  // OthersIcon: require('../../assets/icons/othersIcon.png'),
  // RefreshIcon: require('../../assets/icons/refreshIcon.png'),
  // Hamburger: require('../../assets/icons/hamburger.png'),
  // Bell: require('../../assets/icons/bell.png'),
  // Calendar: require('../../assets/icons/calendar.png'),
  // PlusSquare: require('../../assets/icons/plusSquare.png'),
  // Wrench: require('../../assets/icons/wrench.png'),
  // Crane: require('../../assets/icons/crane.png'),
  // File: require('../../assets/icons/file.png'),
  // Package: require('../../assets/icons/package.png'),
  // Flag: require('../../assets/icons/flag.png'),
  // Users: require('../../assets/icons/users.png'),
  // Copy: require('../../assets/icons/copy.png'),
  // Bookmark: require('../../assets/icons/bookmark.png'),
  // Folder: require('../../assets/icons/folder.png'),
  // RightArrow: require('../../assets/icons/arrowRight.png'),
  // CalendarFilled: require('../../assets/icons/calendarFilled.png'),
  // Filter: require('../../assets/icons/filter.png'),
  // ThreeDotsCircle: require('../../assets/icons/threeDotsCircle.png'),
  // TruckImage: require('../../assets/images/truckImage.png'),
  // PenIcon: require('../../assets/icons/pen.png'),
  // PlusIcon: require('../../assets/icons/plus.png'),
  // MapMarker: require('../../assets/icons/map-marker.png'),
  // PaperClip: require('../../assets/icons/paperclip.png'),
  // Camera: require('../../assets/icons/camera.png'),
  // Requirement: require('../../assets/icons/Requirement.png'),
  // FTService: require('../../assets/icons/FTService.png'),
  // FTEQR: require('../../assets/icons/FTEQR.png'),
  // Vehicles: require('../../assets/icons/3rdEQR.png'),
  // HR: require('../../assets/icons/HR.png'),
  // CrossIcon: require('../../assets/icons/cross.png'),
  // CommentDots: require('../../assets/icons/commentDots.png'),
  // Clock: require('../../assets/icons/clock.png'),
  // Trash: require('../../assets/icons/trash.png'),
  // NoResults: require('../../assets/icons/NoResults.png'),
  // NoImage: require('../../assets/images/NoImage.jpeg'),
  // Relation: require('../../assets/icons/Relation.png'),
  // DisposalWater: require('../../assets/icons/DisposalWater.png'),
  // Replace: require('../../assets/icons/Replace.png'),
  // Splash: require("../../assets/images/TestUser.png"),
  // OverlayPhone: require("../../assets/icons/DisposalWater.png"),
};

export default Images;
